version: '3'
services:
       web:
          build:
             context: ./php
             dockerfile: Dockerfile
          image: php:7.4-apache
          container_name: phpweb
          depends_on:
                  - db
          volumes:
                - ./php:/var/www/html/
          ports:
                 - 8000:80
       db:
              container_name: mysql8
              image: mysql:8.0 
              volumes:
                  - mysql_storage1:/var/lib/mysql
 
              command: --default-authentication-plugin=mysql_native_password
              restart: always
              environment:
                MYSQL_ROOT_PASSWORD: ram
                MYSQL_USER : ram
                MYSQL_PASSWORD: ram
                MYSQL_DATABASE: mydb
              ports:
                      - 6033:3306 

volumes:
        php:
        mysql_storage1:
